name: build docker image and push
on:
  push:
     branches:
      - release-1.0.0
jobs:
   build_and_push:
     runs-on: ubuntu-latest
     steps:
       - name: checkout the code 
         uses: actions/checkout@v4
        
       - name: login into dockerhub
         uses: actions/docker-login@v3
         with:
           username: ${{vars.DOCKER_USERNAME}}
           password: ${{secrets.DOCKER_PASSWORD}}
           
       - name: build docker image
         run: |
               docker build -t springbootapis:latest .
               docker tag springbootapis:latest ${{vars.DOCKER_USERNAME}}/springbootapis:latest
         
         
       - name: push docker image
         run: docker push ${{vars.DOCKER_USERNAME}}/springbootapis:latest
         
          
           
        
       
       
          
       
 
  
   
    
